In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('weather_by_cities.csv')

In [4]:
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [6]:
# filter by cities
df[df['city']=='new york']

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

In [8]:
df[df['city']=='new york'].temperature.max()

np.int64(36)

In [14]:
# group by
df.groupby('city').temperature.max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [15]:
df.groupby('city').temperature.mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

Group by function

In [29]:
df["group"]=df["temperature"].apply(
    lambda x: "80-90" if 80 <= x <= 90 else "50-60" if 50 <= x <= 60 else "Others"
)

In [30]:
df

         day      city  temperature  windspeed   event   group
0   1/1/2017  new york           32          6    Rain  Others
1   1/2/2017  new york           36          7   Sunny  Others
2   1/3/2017  new york           28         12    Snow  Others
3   1/4/2017  new york           33          7   Sunny  Others
4   1/1/2017    mumbai           90          5   Sunny   80-90
5   1/2/2017    mumbai           85         12     Fog   80-90
6   1/3/2017    mumbai           87         15     Fog   80-90
7   1/4/2017    mumbai           92          5    Rain  Others
8   1/1/2017     paris           45         20   Sunny  Others
9   1/2/2017     paris           50         13  Cloudy   50-60
10  1/3/2017     paris           54          8  Cloudy   50-60
11  1/4/2017     paris           42         10  Cloudy  Others

In [2]:
# concat

In [7]:
bd_weather = pd.DataFrame({
    'city': ['Dhaka', 'Chittagong', 'Khulna'],
    'temperature': [32, 29, 31],
    'humidity': [75, 82, 70]
})

us_weather = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'temperature': [28, 31, 24],
    'humidity': [65, 45, 72]
})

In [8]:
bd_weather

         city  temperature  humidity
0       Dhaka           32        75
1  Chittagong           29        82
2      Khulna           31        70

In [9]:
us_weather

          city  temperature  humidity
0     New York           28        65
1  Los Angeles           31        45
2      Chicago           24        72

In [12]:
pd.concat([bd_weather,us_weather],ignore_index=True)

          city  temperature  humidity
0        Dhaka           32        75
1   Chittagong           29        82
2       Khulna           31        70
3     New York           28        65
4  Los Angeles           31        45
5      Chicago           24        72

In [15]:
df = pd.concat([bd_weather,us_weather],keys=['BD','USA'])

In [16]:
df

              city  temperature  humidity
BD  0        Dhaka           32        75
    1   Chittagong           29        82
    2       Khulna           31        70
USA 0     New York           28        65
    1  Los Angeles           31        45
    2      Chicago           24        72

In [17]:
df.index

MultiIndex([( 'BD', 0),
            ( 'BD', 1),
            ( 'BD', 2),
            ('USA', 0),
            ('USA', 1),
            ('USA', 2)],
           )

In [18]:
df.loc['BD']

         city  temperature  humidity
0       Dhaka           32        75
1  Chittagong           29        82
2      Khulna           31        70

In [20]:
df.loc['BD',0]

city           Dhaka
temperature       32
humidity          75
Name: (BD, 0), dtype: object

In [25]:
# DataFrame 1: City and Temperature
df_temp = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'temperature': [28, 31, 24]
})

# DataFrame 2: City and Wind Speed
df_wind = pd.DataFrame({
    'city': ['New York', 'Chicago'],
    'windspeed': [12, 18]
})

In [26]:
pd.merge(df_temp,df_wind,on='city')

       city  temperature  windspeed
0  New York           28         12
1   Chicago           24         18

In [28]:
pd.merge(df_temp,df_wind,how='outer')

          city  temperature  windspeed
0      Chicago           24       18.0
1  Los Angeles           31        NaN
2     New York           28       12.0

In [32]:
pd.merge(df_temp,df_wind,how='inner')

       city  temperature  windspeed
0  New York           28         12
1   Chicago           24         18

how='inner' ----> by default

In [33]:
pd.merge(df_temp,df_wind,how='left')

          city  temperature  windspeed
0     New York           28       12.0
1  Los Angeles           31        NaN
2      Chicago           24       18.0

In [34]:
pd.merge(df_temp,df_wind,how='right')

       city  temperature  windspeed
0  New York           28         12
1   Chicago           24         18