In [26]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('weather_data.csv')

In [4]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          9 non-null      str
 1   temperature  5 non-null      float64
 2   windspeed    5 non-null      float64
 3   event        7 non-null      str
dtypes: float64(2), str(2)
memory usage: 420.0 bytes

In [9]:
df.day = pd.to_datetime(df.day)

In [13]:
df.dtypes

day            datetime64[us]
temperature           float64
windspeed             float64
event                     str
dtype: object

The pd.to_datetime function in pandas is used to convert to a pandas datetime object.

In [16]:
df.set_index('day',inplace=True)

In [17]:
df.index

DatetimeIndex(['2017-01-01', '2017-01-04', '2017-01-05', '2017-01-06',
               '2017-01-07', '2017-01-08', '2017-01-09', '2017-01-10',
               '2017-01-11'],
              dtype='datetime64[us]', name='day', freq=None)

In [18]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [35]:
df.fillna({'temperature':df['temperature'].mean(),'windspeed':df['windspeed'].mean()})

            temperature  windspeed   event
day
2017-01-01        32.00       6.00    Rain
2017-01-04        33.22       9.00   Sunny
2017-01-05        28.00       8.42    Snow
2017-01-06        33.22       7.00     NaN
2017-01-07        32.00       8.42    Rain
2017-01-08        33.22       8.42   Sunny
2017-01-09        33.22       8.42     NaN
2017-01-10        34.10       8.10  Cloudy
2017-01-11        40.00      12.00   Sunny

In [43]:
df.temperature = df.temperature.ffill()

In [44]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06         28.0        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09         32.0        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [45]:
df.windspeed.bfill()

day
2017-01-01     6.0
2017-01-04     9.0
2017-01-05     7.0
2017-01-06     7.0
2017-01-07     8.1
2017-01-08     8.1
2017-01-09     8.1
2017-01-10     8.1
2017-01-11    12.0
Name: windspeed, dtype: float64

In [47]:
df.windspeed

day
2017-01-01     6.0
2017-01-04     9.0
2017-01-05     NaN
2017-01-06     7.0
2017-01-07     NaN
2017-01-08     NaN
2017-01-09     NaN
2017-01-10     8.1
2017-01-11    12.0
Name: windspeed, dtype: float64

In [48]:
df.windspeed.interpolate() # Linear interpolation

day
2017-01-01     6.000
2017-01-04     9.000
2017-01-05     8.000
2017-01-06     7.000
2017-01-07     7.275
2017-01-08     7.550
2017-01-09     7.825
2017-01-10     8.100
2017-01-11    12.000
Name: windspeed, dtype: float64

In [49]:
df.dropna()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [52]:
df.dropna(how='all')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06         28.0        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09         32.0        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

how='all' removes only those rows where every column is NaN

In [65]:
df = pd.read_csv('weather.csv')

In [62]:
df

          day  temperature  windspeed     event
0  01/01/2017           32          6      Rain
1  02/01/2017       -99999          7     Sunny
2  03/01/2017           28     -99999      Snow
3  04/01/2017       -99999          7  no event
4  05/01/2017           32     -99999      Rain
5  06/01/2017           31          2     Sunny
6  06/01/2017           34     -88888  no event

In [66]:
df = df.replace([-99999,-88888],np.nan)

In [67]:
df

          day  temperature  windspeed     event
0  01/01/2017         32.0        6.0      Rain
1  02/01/2017          NaN        7.0     Sunny
2  03/01/2017         28.0        NaN      Snow
3  04/01/2017          NaN        7.0  no event
4  05/01/2017         32.0        NaN      Rain
5  06/01/2017         31.0        2.0     Sunny
6  06/01/2017         34.0        NaN  no event

In [68]:
df['temperature'].replace(np.nan,0)

0    32.0
1     0.0
2    28.0
3     0.0
4    32.0
5    31.0
6    34.0
Name: temperature, dtype: float64

In [69]:
df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'performance': ['Excellent', 'Good', 'Average', 'Poor', 'Good']
})
df

   student performance
0    Alice   Excellent
1      Bob        Good
2  Charlie     Average
3    David        Poor
4      Eva        Good

In [70]:
df = df.replace({'Excellent':90, 'Good':80, 'Average':75, 'Poor':60})

In [71]:
df

   student performance
0    Alice          90
1      Bob          80
2  Charlie          75
3    David          60
4      Eva          80