In [1]:
# import necessary library
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')

In [3]:
# return 1st 5 rows
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [4]:
# return any 5 rows
df.sample(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.2,291.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.0,2202.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada

In [5]:
# return the last n rows of a DataFrame
df.tail(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [6]:
# check the dimensionality of the DataFrame
df.shape

(37, 10)

total 37 rows and 10 columns

In [7]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='str')

In [8]:
df.industry.unique()

<StringArray>
['Bollywood', 'Hollywood']
Length: 2, dtype: str

movies are from 2 unique industry

In [9]:
df.language.unique()

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str

In [10]:
df['language'].unique()

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str

In [11]:
df['language'].nunique()

5

In [12]:
df['industry'].value_counts() # count the frequency of each unique value in the industry column

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [13]:
df['language'].value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [14]:
df[['title','industry','imdb_rating']]

                                          title   industry  imdb_rating
0                               Pather Panchali  Bollywood          8.3
1   Doctor Strange in the Multiverse of Madness  Hollywood          7.0
2                         Thor: The Dark World   Hollywood          6.8
3                               Thor: Ragnarok   Hollywood          7.9
4                       Thor: Love and Thunder   Hollywood          6.8
5                      The Shawshank Redemption  Hollywood          9.3
6                                  Interstellar  Hollywood          8.6
7                      The Pursuit of Happyness  Hollywood          8.0
8                                     Gladiator  Hollywood          8.5
9                                       Titanic  Hollywood          7.9
10                        It's a Wonderful Life  Hollywood          8.6
11                                       Avatar  Hollywood          7.8
12                                The Godfather  Hollywood          9.2
13                              The Dark Knight  Hollywood          9.0
14                             Schindler's List  Hollywood          9.0
15                                Jurassic Park  Hollywood          8.2
16                                     Parasite  Hollywood          8.5
17                            Avengers: Endgame  Hollywood          8.4
18                       Avengers: Infinity War  Hollywood          8.4
19           Captain America: The First Avenger  Hollywood          6.9
20          Captain America: The Winter Soldier  Hollywood          7.8
21                  Dilwale Dulhania Le Jayenge  Bollywood          8.0
22                                     3 Idiots  Bollywood          8.4
23                     Kabhi Khushi Kabhie Gham  Bollywood          7.4
24                             Bajirao Mastani   Bollywood          7.2
25                             Taare Zameen Par  Bollywood          8.3
26                          Munna Bhai M.B.B.S.  Bollywood          8.1
27                                           PK  Bollywood          8.1
28                                        Sanju  Bollywood          NaN
29                            The Kashmir Files  Bollywood          8.3
30                            Bajrangi Bhaijaan  Bollywood          8.1
31                                       Race 3  Bollywood          1.9
32                                    Shershaah  Bollywood          8.4
33                             K.G.F: Chapter 2  Bollywood          8.4
34                    Pushpa: The Rise - Part 1  Bollywood          7.6
35                                          RRR  Bollywood          8.0
36                     Baahubali: The Beginning  Bollywood          8.0

In [15]:
df[(df.release_year <= 2010) & (df.release_year >= 2000)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [16]:
df[df.studio == 'Marvel Studios'] # returns all rows where studio is "Marvel Studios".

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [17]:
# generate descriptive statistics
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [18]:
# get a concise summary of the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     str
 1   industry      37 non-null     str
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     str
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     str
 8   currency      37 non-null     str
 9   language      37 non-null     str
dtypes: float64(3), int64(1), str(6)
memory usage: 3.0 KB

In [19]:
# find maximum imdb rating
df.imdb_rating.max()

np.float64(9.3)

In [20]:
# find minimum imdb rating
df.imdb_rating.min()

np.float64(1.9)

In [21]:
df['release_year'].apply(lambda x:2023-x)

0     68
1      1
2     10
3      6
4      1
5     29
6      9
7     17
8     23
9     26
10    77
11    14
12    51
13    15
14    30
15    30
16     4
17     4
18     5
19    12
20     9
21    28
22    14
23    22
24     8
25    16
26    20
27     9
28     5
29     1
30     8
31     5
32     2
33     1
34     2
35     1
36     8
Name: release_year, dtype: int64

In [22]:
df['profit'] = df['revenue'] - df['budget']

In [23]:
df['profit']

0     30000.00
1       754.80
2       479.80
3       674.00
4       420.00
5        48.30
6       536.80
7       252.10
8       357.50
9      2002.00
10        0.12
11     2610.00
12      283.80
13      821.00
14      300.20
15      983.00
16      247.60
17     2398.00
18     1648.00
19      153.90
20      537.40
21     1600.00
22     3450.00
23      970.00
24        2.10
25     1230.00
26      310.00
27     7690.00
28        4.90
29     3159.00
30    10790.00
31        1.30
32      450.00
33       11.50
34        1.60
35        6.50
36        4.70
Name: profit, dtype: float64

In [24]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [25]:
df.set_index('title',inplace=True)

In [26]:
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
title,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0

In [27]:
df.loc['Pather Panchali']

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
profit                            30000.0
Name: Pather Panchali, dtype: object

In [28]:
df.loc[['Pather Panchali', 'Doctor Strange in the Multiverse of Madness']]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
title,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8

In [29]:
df.iloc[0]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
profit                            30000.0
Name: Pather Panchali, dtype: object

In Pandas, both .loc and .iloc are used for selecting subsets of data from a DataFrame.

loc → Label-based indexing .iloc → Integer position-based indexing

In [30]:
df.reset_index(inplace=True)

In [31]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0

In [32]:
df.iloc[2:5]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0