In [22]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('stock_data.csv',skiprows=1)

skiprows: Line numbers to skip (0-indexed) or number of lines to skip (int) at the start of the file.

In [9]:
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

Alternative: header

In [ ]:
df=pd.read_csv('stock_data.csv',header=1)

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [18]:
df=pd.read_csv('stock_data.csv',header=1,names=['stock_symbol','eps','revenue','price','people'])

In [19]:
df

  stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

names=[...]

Assigns custom column names instead of reading them from the file.

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   stock_symbol  5 non-null      str
 1   eps           5 non-null      str
 2   revenue       5 non-null      int64
 3   price         5 non-null      str
 4   people        5 non-null      str
dtypes: int64(1), str(4)
memory usage: 332.0 bytes

In [37]:
df=pd.read_csv('stock_data.csv',skiprows=1,na_values={'eps':'not available','price':'n.a.','revenue':-1,'people':'n.a.'})

na_values: treat specific strings as missing values (NaN) in selected columns.

In [38]:
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   tickers  5 non-null      str
 1   eps      4 non-null      float64
 2   revenue  4 non-null      float64
 3   price    4 non-null      float64
 4   people   4 non-null      str
dtypes: float64(3), str(2)
memory usage: 332.0 bytes

In [48]:
df=pd.read_csv('stock_data.csv',header=1,na_values=['not available',-1,'n.a.'])

In [49]:
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [50]:
df['pe'] = df['price']/df['eps']

In [51]:
df['pe']

0    30.373832
1    14.099783
2          NaN
3          NaN
4          NaN
Name: pe, dtype: float64

In [52]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people', 'pe'], dtype='str')

In [ ]:
df.to_csv("pe_ratio.csv", index=False, header=False) # export to csv

In [58]:
# read excel file

In [65]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [71]:
# Read a specific sheet by name
df_movies = pd.read_excel('movies_db.xlsx','movies')

In [72]:
df_movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [81]:
df_financials = pd.read_excel('movies_db.xlsx','financials')

In [82]:
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [83]:
df_financials['currency'].unique()

<StringArray>
['INR', 'USD', '$$', 'Dollars']
Length: 4, dtype: str

In [84]:
df_financials['currency'] = df_financials['currency'].replace({'$$':'USD','Dollars':'USD'})

In [85]:
df_financials['currency'].unique()

<StringArray>
['INR', 'USD']
Length: 2, dtype: str

In [86]:
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [87]:
df_merged = pd.merge(df_movies, df_financials, on='movie_id')

In [88]:
df_merged.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

This way we can merge 2 different dataframes based on a common column.

In [92]:
df = pd.DataFrame({'student_id':[1,2,3],
'name':['Joy','Zim','Duke']})

In [93]:
df

   student_id  name
0           1   Joy
1           2   Zim
2           3  Duke